first_name = str(input('Введите имя: '))
city = str(input('Укажите город: '))
city_area = str(input('Укажите область: '))
address = str(input('Укажите адрес: '))
post_index = str(input('Укажите индекс: '))
phone_num = str(input('Введите номер телефона: '))
spec = str(input('Укажите специальность: '))
print('Имя:',first_name)
print('Адрес:', post_index, city_area,'обл.','г.',city, address)
print('Номер телефона:', phone_num)
print('Специальность:', spec)
